### ISSUE TITLE
Too strict gammapy compatibility?

### ISSUE THREAD

**Issue by matthew-w-lundy** [VERITAS-Observatory/gammapy-tools#31]
"gammapy==1.1" seems very strict, can this be opened to gammapy>1.1 to allow for 1.3 installs?

**Comment by steob92** [comment]
That's in requirements.txt? The code has only been tested with 1.1 and 1.2. 

We're using pyproject.toml:
https://github.com/VERITAS-Observatory/gammapy-tools/blob/ccacd80b784da0827bddf2255b25597be6c72d76/pyproject.toml#L41

requirements.txt will be phased out. The only strict requirement at the moment is SciPy:
https://github.com/VERITAS-Observatory/gammapy-tools/blob/ccacd80b784da0827bddf2255b25597be6c72d76/pyproject.toml#L43C6-L43C19

See:
https://github.com/gammapy/gammapy/discussions/5034#discussioncomment-8982228

**Comment by matthew-w-lundy** [comment]
I was looking on main in the pyproject. I see that you have addressed this in a branch that hasn't been merged

https://github.com/VERITAS-Observatory/gammapy-tools/blob/fcf62362592598743b68c05e405a2b416d938f73/pyproject.toml#L33C1-L33C20

**Comment by matthew-w-lundy** [comment]
But actually this may be too weak a requirement knowing that 0.18 is incompatible

**Comment by steob92** [comment]
I seem to remember a bug in gammapy v1.0.2. I've explicitly set the requirement to gammapy>=1.1 
[771cd3e](https://github.com/VERITAS-Observatory/gammapy-tools/commit/771cd3edfce65613d70fd5478e842325ac897e3a)
