### ISSUE TITLE
Cannot Rerun prepare datasets 

### ISSUE THREAD

**Issue by matthew-w-lundy** [VERITAS-Observatory/gammapy-tools#35]
`prepare_dataset `does not allow the user to pass an overwrite flag to copy_obs which means that to re-run prepare datasets you need to delete your index files. 

https://github.com/VERITAS-Observatory/gammapy-tools/blob/6c24bc96abf49c74fae55d9ad4040a363bc0790e/gammapy_tools/make_background/prepare_data.py#L51C1-L62C1

**Comment by steob92** [comment]
This is mainly a gammapy issue. There is no overwrite flag for `copy_obs`.  My philosophy was not to trust that the user hasn't passed some important directory by accident and instead require that they manually delete it.

We could implement our own check to see if there are index files, include an overwrite flag and/or have them enter "yes" to delete or something.

**Comment by steob92** [comment]
hmm. Seems to work now. Must be a new addition. Added to:
[ffca60a](https://github.com/VERITAS-Observatory/gammapy-tools/commit/ffca60ac9587b1a90e55bca2ddb5830e0e445038)

We'll make a new release with #34  and #36 (and other errors that come up with testing...)
