### ISSUE TITLE
ON counts discrepancy with ED

### ISSUE THREAD

**Issue by samanthalwong** [VERITAS-Observatory/gammapy-tools#51]
For point-like validation sources, ON counts are approximately +/- 1 count/run different from ED (as far as I've seen, there's always fewer counts in gammapy). It would be nice to know which events these are and why they're being thrown out in gammapy (i.e., is it the SafeMaskMaker, is it a rounding/binning issue, etc.). 

Since the DL3 files are produced in ED, the initial event list, which corresponds to the event list after gamma/hadron cuts from anasum, should be identical. However, gammapy does not track the event numbers (IDs) through analysis and only tracks the integer number of events in each spatial/energy bin.

**Comment by samanthalwong** [comment]
See [this presentation ](https://veritas.sao.arizona.edu/GammaWiki/images/6/6a/Gammapyrbmjune.pdf)for more details & numbers!

**Comment by steob92** [comment]
On slide 9, are you using the latest DL3 files? There was a point-like vs full enclosure issue that was resolved by using the latest DL3 files.

**Comment by samanthalwong** [comment]
No, those are the old ones (so that particlular issue is resolved as far as I know), but the counts/significance stuff still is a problem with the updated files
