### ISSUE TITLE
Arbitrarily losing events

### ISSUE THREAD

**Issue by samanthalwong** [VERITAS-Observatory/gammapy-tools#52]
May be related to issue #51

Changing the energy threshold to non-physically small or large values (e.g., going up from 0.0001 TeV to 0.01 TeV I gain counts) or changing from 2D to 3D bkgs changes the number of ON counts in an unpredictable way. 

This _may_ have something to do with an improper implementation of `energy_axis` and `energy_axis_true` in [gammapy's RBM tutorial](https://docs.gammapy.org/1.2/tutorials/analysis-2d/ring_background.html) or could come from improper rounding (see this [gammapy PR](https://github.com/gammapy/gammapy/pull/5366)), but it's likely more than that.

**Comment by matthew-w-lundy** [comment]
So I looked into this and if you look at run 64082 you see a difference of 3 events that flick on and then off as you move from 0.0126 TeV, to 0.02 TeV. The events you appear to lose are 12834, 481209, and 532391. These events have the lowest energy being at 0.12140787 TeV, 0.12149556 TeV, and 0.1196972 TeV. They all should be above the energy threshold. 

Changing the energy axis true to massively increase the number of bins does not affect this. 

Removing the safe mask maker does not affect this. 

This can be removed by changing the bin locations in the energy axis so there is some issue in gammapy with how the energy axis is doing the selection of which bins to include and how it's binning the lowest energy events. 

I will run this again with another run to make sure that this is always the lowest energy events causing the issue. 

Here is what the peek looks like for those event:

![image](https://github.com/user-attachments/assets/5f4aba8f-1040-4837-aa26-d82e6f5877d4)

And here is the info 
![image](https://github.com/user-attachments/assets/fb25d521-3256-4992-8e47-3edf6d398fd4)

**Comment by samanthalwong** [comment]
See #51
